Milestone 1
Haywhizzz/Tic-Tac-Toe pull request #1
Opened 2020-08-13 13:55 UTC by mcihadkurel

### Tic Tac Toe Has Started!

1-) Created all linter folders
2-) Added all required working folders

2020-08-13 21:32 UTC, kitpao requested changes
# 👋 Hello @mcihadkurel and @Haywhizzz 

You did well following the new Git Flow 👏 

You are missing some details in your setup, please check them below 🔽 

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-08-13 21:32 UTC, kitpao commented on bin/main.rb
> +p 'Hello World!'
- [ ] Please follow the [indicated guide in Pathwright](https://commandercoriander.net/blog/2013/02/16/making-a-ruby-script-executable/) To make your file executable
![image](https://user-images.githubusercontent.com/53256139/90189063-2685a080-dd82-11ea-91a3-efb88bff9568.png)

2020-08-13 21:32 UTC, kitpao commented on .rubocop.yml
> +  Enabled: false
- [ ] Remember you should not change the files for the linters, please use the original files in [Microverse Repo](https://github.com/microverseinc/linters-config/tree/master/ruby) as stated in Pathwright
![image](https://user-images.githubusercontent.com/53256139/90188486-26d16c00-dd81-11ea-8269-650ee4ab550d.png)

2020-08-14 21:19 UTC, krys2fa commented
## Good job so far @mcihadkurel and @Haywhizzz  👏 
Your project has a descriptive PR and good commit messages as well. 💪 

### Status: Changes Required ♻️ 
There's just one more change to make to get this approved. 

- [REQUIRED ] The executable file should work. That is it should display a message when `bin/main.rb` is run in the terminal ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/execute_bin.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)).

That's all. Please request for another review after implementing the changes.

Happy Coding 🖥️  😃 

###### You can contact me on slack (Chris Amanor) for any clarification.

2020-08-15 22:00 UTC, Haywhizzz commented
We have made the main.rb executable

2020-08-15 23:04 UTC, voscarmv approved these changes
# Status: Project Approved ✨ 😎👍 💯 ✔️

- Excellent work applying the requested changes!

### You may merge this branch and move forward ⛙🛣

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-08-17 07:37 UTC, merged